### ISSUE TITLE
Pretrained models

### ISSUE THREAD

**Issue by otsab19** [BioMedAI-UCSC/InverseSR#13]
@jueqiw What are the pre trained vae and vgg16  models being used here? There are no files in the drive. Is the files somewhere or its being trained by yourself?

**Comment by otsab19** [comment]
nvm found it

**Comment by Willow-WYL** [comment]
I encountered the same question! Where did you find them?

**Comment by Willow-WYL** [comment]
@otsab19 Hi! I have encountered the same question! Where did you find vae?

**Comment by otsab19** [comment]
https://github.com/BioMedAI-UCSC/InverseSR/issues/9

**Comment by Willow-WYL** [comment]
@otsab19 I found vgg in that, what about vae? Thank you so much!!!

**Comment by jueqiw** [comment]
@Willow-WYL Can you point out where in the code use the vae? Thanks!

**Comment by Willow-WYL** [comment]
@jueqiw sorry! i didnt see your reply last week! when i tried to test the model DDIM, I run the InverseSR_DDIM.sh, got the error as follows: FileNotFoundError: [Errno 2] No such file or directory: '/InverseSR-main/data/trained_models/vae/data/model.pth'

**Comment by Willow-WYL** [comment]
@jueqiw i believe it means that there should be a pretrained vae model?

**Comment by jueqiw** [comment]
@Willow-WYL Can you tell me which line and file caused that error?

**Comment by Willow-WYL** [comment]
@jueqiw utils.py line121

**Comment by aruiplex** [comment]
Hi, does anyone solve this issue? I still stuck at `OSError: No such file or directory: 'InverseSR/data/trained_models/vae'`

**Comment by jueqiw** [comment]
Hi, I have uploaded vae weight to the Google Drive folder, you can find that directory here
