### ISSUE TITLE
where can I find the pretrained model?

### ISSUE THREAD

**Issue by Willow-WYL** [BioMedAI-UCSC/InverseSR#16]
hi author! @jueqiw 
May i ask where i can find the pretrained model "vae and vgg"? I believe they are absent in your downloading link.

**Comment by jueqiw** [comment]
You can find those model vgg here: https://nvlabs-fi-cdn.nvidia.com/stylegan2-ada-pytorch/pretrained/metrics/vgg16.pt

The rest things you need should be able to find here: https://drive.google.com/drive/folders/110l68um6gUJzECIv0AyF-4Fcw0rrQgA9

Thanks!
