### ISSUE TITLE
Sharing of precomputed latent vectors/stats

### ISSUE THREAD

**Issue by jakub-prokop** [BioMedAI-UCSC/InverseSR#3]
Hi!
Would you mind sharing latent vectors file (_latent_vector_ddpm_samples_100000.pt_) or just the precomputed stats, that serve as the initialization of the latent code for the InverseSR(decoder) pipeline?

Thanks in advance
Jakub

**Comment by jueqiw** [comment]
Hi Jakub,

Yeah, definitely. I think I put all the params you need to run the model here:
https://drive.google.com/drive/folders/110l68um6gUJzECIv0AyF-4Fcw0rrQgA9?usp=drive_link

I uploaded the `latent_vector_ddpm_samples_100000.pt` whole files in case you might need them in the future. Please don't hesitate to let me know if you have any questions about the code. We can have a Zoom meeting to discuss them.

I will close this issue. If you have further questions about it, feel free to open it again!

Jueqi

**Comment by 06Liz** [comment]
@jakub-prokop Did you find out where this file(latent_vector_ddpm_samples_100000.pt) is?
