### ISSUE TITLE
Incomplete code

### ISSUE THREAD

**Issue by Adele0108** [BioMedAI-UCSC/InverseSR#4]
Dear Jueqi, 

Thanks for sharing this work! However, I noticed that some essential files are missing from the code repository. Specifically, the readme file, dataloader file, and IXI_T1_069.pth file are not included. I would greatly appreciate it if you could kindly upload the complete code for InverseSR, including all the necessary files.

Thank you very much for your attention to this matter. Looking forward to your positive response.

Best regards,
Adele

**Comment by jueqiw** [comment]
Dear Adele,

I am sorry that I previously didn't provide those necessary files. I have uploaded them into the Google Drive:
https://drive.google.com/drive/folders/110l68um6gUJzECIv0AyF-4Fcw0rrQgA9?usp=drive_link

I will close this issue now, but you can also open it if you have any questions.

Jueqi
