### ISSUE TITLE
Mask files

### ISSUE THREAD

**Issue by jakub-prokop** [BioMedAI-UCSC/InverseSR#5]
Hi!
Would you mind sharing the mask files used for acquiring 4mm and 8mm image slices?

Thanks in advance
Jakub

**Comment by jueqiw** [comment]
Sorry about that! I just uploaded them into the google drive folder: https://drive.google.com/drive/folders/110l68um6gUJzECIv0AyF-4Fcw0rrQgA9?usp=drive_link

In the folder of mask: `9.npy` represents the mask for 8mm slices, while `5.npy` represents the mask for 4mm slices.

Again, don't hesitate to let me know if you have any questions when running the code! I will close this issue but you can also reopen it.
