### ISSUE TITLE
Hardware requirements

### ISSUE THREAD

**Issue by jakub-prokop** [BioMedAI-UCSC/InverseSR#6]
Hi!
I'm facing constant memory issues with running the ddim pipeline on my CPU, so I am wondering, what hardware did you run your experiments on? Most importantly, what was your RAM memory size?

Thanks for all previous answers
Jakub

**Comment by jueqiw** [comment]
You might not want to hear that, I run the experiments on a cluster with nodes with 188GB of RAM. The pretrained brain latent diffusion model we used is trained on 80 GB memory of GPU, so I guess it can be run on 80GB memory.

**Comment by jakub-prokop** [comment]
That explains my problems a bit :) Thanks! I close the issue.
