### ISSUE TITLE
VGG16 Weights

### ISSUE THREAD

**Issue by jiaqiw01** [BioMedAI-UCSC/InverseSR#9]
Hi, I'm wondering if you have the vgg16.pt file as I cannot find it in the google drive or is it fine to use any vgg16 weights online? Thank you in advance!

**Comment by jueqiw** [comment]
Hi!

Thanks for your interest in our work! You can download the vgg16 weights from: https://nvlabs-fi-cdn.nvidia.com/stylegan2-ada-pytorch/pretrained/metrics/vgg16.pt

Please don't hesitate to let me know if you run into any issues when running the code.

Jueqi
